# title: Just the Docs
# description: A Jekyll theme for documentation
# baseurl: "/just-the-docs" # the subpath of your site, e.g. /blog
# url: "https://pmarsceill.github.io" # the base hostname & protocol for your site, e.g. http://example.com

theme: just-the-docs

defaults:
  - scope:
      path: "/REPO_NAME/"
    values:
      layout: "default"

# Set a path/url to a logo that will be displayed instead of the title
logo: "https://www.taylor.edu/img/tu-logo.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/

# Aux links for the upper right navigation
aux_links:
  "Theme Docs":
    - "//github.com/pmarsceill/just-the-docs"
  "Taylor Website":
    - "https://www.taylor.edu"

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false/nil
heading_anchors: true

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020 Taylor University Web Team"

# Color scheme currently only supports "dark" or nil (default)
# color_scheme: "dark"

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
# ga_tracking: UA-5555555-55

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true

permalink: pretty